[package]
name = "my-server"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
anyhow = "1.0.86"
ctrlc = "3.4.4"
gstreamer = "0.22.4"
libc = "0.2.155"
my-common = { path = "../my-common" }
my-workspace-hack = { version = "0.1", path = "../my-workspace-hack" }
